Ci pipeline dev (#75)
* Build draft

* Fix tag

* Upload artifact test

* Create a draft tag

* Fix file name

* TESt upload

* Allow tag to exist

* Fix file name

* Create latest bloom

* pr instead of draft

diff --git a/.github/workflows/build-prerelease.yml b/.github/workflows/build-prerelease.yml
--- a/.github/workflows/build-prerelease.yml
+++ b/.github/workflows/build-prerelease.yml
@@ -2,6 +2,7 @@ name: Build Prerelease
 
 on:
   workflow_dispatch:
+  pull_request:
 jobs:
   buildAndRelease:
     runs-on: ubuntu-latest
@@ -12,19 +13,20 @@ jobs:
         uses: jetify-com/devbox-install-action@v0.12.0
 
       - name: Build with devbox
-        run: devbox run build -ldflags="-X 'github.com/silogen/cluster-bloom/cmd.Version=pre-${GITHUB_REF_NAME}-${GITHUB_SHA}'"
+        run: |
+          devbox run build -ldflags="-X 'github.com/silogen/cluster-bloom/cmd.Version=pre-${GITHUB_REF_NAME}-${GITHUB_SHA}'"
+          cp dist/bloom dist/bloom-"${GITHUB_REF_NAME}-${GITHUB_RUN_NUMBER}-${GITHUB_SHA}"
       
+      - name: Create Tag
+        run: |
+          git tag pr-${{ github.ref_name }}
+          git push origin pr-${{ github.ref_name }} || true # allow failure if tag already exists
+
       - name: Create GitHub Release
         uses: softprops/action-gh-release@v2
         with:
-          tag_name: ${{ github.ref_name }}
+          tag_name: pr-${{ github.ref_name }}
           prerelease: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-
-      - name: Upload Release Assets
-        uses: softprops/action-gh-release@v2
-        with:
           files: dist/*
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
